version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: gbibliotecadb
      MYSQL_USER: root
      MYSQL_PASSWORD: admin2025
      MYSQL_ROOT_PASSWORD: admin2025
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql-db          # Host del servicio MySQL
      PMA_PORT: 3306        # Puerto de MySQL
    ports:
      - "8081:80"

  api-sgb:
    build: .
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/gbibliotecadb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin2025

volumes:
  db-data:
